# Generated by Django 5.2.11 on 2026-03-27

from django.contrib.auth.hashers import make_password
from django.db import migrations


def hash_passwords(apps, schema_editor):
    """Hash all existing plaintext media passwords.

    Since the database is known to contain only plaintext passwords,
    we hash unconditionally without identify_hasher() checks.
    """
    Media = apps.get_model("files", "Media")
    batch_size = 500
    updated = 0

    for media in Media.objects.exclude(password="").exclude(password__isnull=True).iterator(chunk_size=batch_size):
        media.password = make_password(media.password)
        media.save(update_fields=["password"])
        updated += 1

    if updated:
        print(f"  Hashed {updated} media password(s)")


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0017_widen_password_field"),
    ]

    operations = [
        migrations.RunPython(hash_passwords, migrations.RunPython.noop),
    ]
