# Generated by Django 5.2.11 on 2026-03-27

from django.contrib.auth.hashers import identify_hasher, make_password
from django.db import migrations


def hash_passwords(apps, schema_editor):
    """Hash all existing plaintext media passwords.

    Uses identify_hasher() to skip already-hashed values, making the
    migration idempotent and safe to re-run.
    """
    Media = apps.get_model("files", "Media")
    batch_size = 500
    updated = 0

    for media in Media.objects.exclude(password="").exclude(password__isnull=True).iterator(chunk_size=batch_size):
        try:
            identify_hasher(media.password)
            continue  # Already hashed, skip
        except ValueError:
            pass  # Plaintext — needs hashing
        media.password = make_password(media.password)
        media.save(update_fields=["password"])
        updated += 1

    if updated:
        print(f"  Hashed {updated} media password(s)")


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0017_widen_password_field"),
    ]

    operations = [
        migrations.RunPython(hash_passwords, migrations.RunPython.noop),
    ]
